Repository thekeele/bitfeels, pull requests merged in 2018-03, with the labels that each got.

#33 Displaying database stats
  ex_feels/assets/static/images/brain.jpg
  ex_feels/lib/ex_feels/feel.ex
  ex_feels/lib/ex_feels/stat.ex
  ex_feels/lib/ex_feels/twitter/tweet.ex
  ex_feels/lib/ex_feels/twitter/user.ex
  ex_feels/lib/ex_feels_web/controllers/home_controller.ex
  ex_feels/lib/ex_feels_web/templates/home/home.html.eex
  ex_feels/lib/ex_feels_web/templates/layout/app.html.eex
  ex_feels/lib/ex_feels_web/templates/layout/header.html.eex
  ex_feels/mix.exs
  ex_feels/mix.lock
Labels: bulma, elixir, help wanted, phoenix, waiting-on-pr

#36 Layout and CSS Tweaks
  ex_feels/assets/css/app.scss
  ex_feels/lib/ex_feels_web/templates/feel/feel.html.eex
Labels: enhancement, ready-for-review

#38 migrate stats time to integer
  ex_feels/priv/repo/migrations/20180310013957_alter_stats_modify_time_integer.exs
Labels: ready-for-review

#37 Plotting feels (for reals)
  ex_feels/assets/css/timefeels.scss
  ex_feels/assets/js/timefeels.js
  ex_feels/lib/ex_feels/stat.ex
  ex_feels/lib/ex_feels_web/views/stats_view.ex
  py_feels/binary/time_series.py
Labels: feature, javascript, ready-for-review

#39 Release/v1.5
  ex_feels/assets/brunch-config.js
  ex_feels/assets/css/app.scss
  ex_feels/assets/css/timefeels.scss
  ex_feels/assets/js/app.js
  ex_feels/assets/js/timefeels.js
  ex_feels/assets/package.json
  ex_feels/assets/static/images/brain.jpg
  ex_feels/config/config.exs
  ex_feels/lib/ex_feels/application.ex
  ex_feels/lib/ex_feels/feel.ex
  ex_feels/lib/ex_feels/stat.ex
  ex_feels/lib/ex_feels/twitter/tweet.ex
  ex_feels/lib/ex_feels/twitter/user.ex
  ex_feels/lib/ex_feels_web/controllers/feel_controller.ex
  ex_feels/lib/ex_feels_web/controllers/home_controller.ex
  ex_feels/lib/ex_feels_web/controllers/stats_controller.ex
  ex_feels/lib/ex_feels_web/router.ex
  ex_feels/lib/ex_feels_web/templates/feel/feel.html.eex
  ex_feels/lib/ex_feels_web/templates/home/home.html.eex
  ex_feels/lib/ex_feels_web/templates/layout/app.html.eex
  ex_feels/lib/ex_feels_web/twitter_api.ex
  ex_feels/lib/ex_feels_web/twitter_api/auth.ex
  ex_feels/lib/ex_feels_web/twitter_api/fetch.ex
  ex_feels/lib/ex_feels_web/twitter_api/request.ex
  ex_feels/lib/ex_feels_web/twitter_api/search.ex
  ex_feels/lib/ex_feels_web/twitter_api/worker.ex
  ex_feels/lib/ex_feels_web/views/feel_view.ex
  ex_feels/lib/ex_feels_web/views/stats_view.ex
  ex_feels/mix.exs
  ex_feels/mix.lock
  py_feels/.gitignore
  py_feels/binary/binary_classifier.py
  py_feels/binary/reclassify.py
  py_feels/binary/time_series.py
Labels: ready-for-review
